In [6]:
from sindy_library_numpy import SINDyNew
import numpy as np
import itertools


In [8]:
sl = SINDyNew(   latent_dim=1,
                 include_biases=False,
                 include_states=False,
                 include_sin=False,
                 include_cos=False,
                 include_multiply_pairs=False,
                 poly_order=2,
                 include_sqrt=False,
                 include_inverse=False,
                 include_sign_sqrt_of_diff=False,)

In [9]:
sl.feature_names

['z0*z0']

In [24]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
theta = sl.transform(x)
theta

array([[ 1],
       [16]])

In [63]:
theta.shape

(3, 4)

In [90]:
latent_dim = 3

In [91]:
possible_indicies = list(range(latent_dim))
possible_indicies

[0, 1, 2]

In [92]:
permuts = itertools.product(possible_indicies, possible_indicies)

In [95]:
for p in permuts:
    print(p)

(0, 1)
(0, 2)
(1, 0)
(1, 2)
(2, 0)
(2, 1)


In [96]:
permuts = [p for p in permuts if not p[0] == p[1]]
permuts

[(0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1)]

In [97]:
list(set([tuple(sorted(list(p))) for p in permuts]))

[(0, 1), (0, 2), (1, 2)]

In [ ]:
permuts = [p for p in permuts if not p[0] == p[1]]
self.idx_combis_non_commutative = permuts
self.idx_combis_commutative = list(set([tuple(sorted(list(p))) for p in permuts]))



if self.poly_order == 2:
    self.candidate_functions.append(self.poly_deg_2)
    names = []
    for i in range(self.latent_dim):
        for j in range(i, self.latent_dim):

    self.feature_names.extend(names)


In [ ]:
def poly_deg_2(z):
    result = 
    for i in range(latent_dim):
        for j in range(i, latent_dim):
            print(res
            res = z[:,i]*z[:,j]
            res = res.reshape(-1, 1)
            result.append(res)
    return np.concatenate(result, axis=1)

In [25]:
from sindy_library import *
import torch

In [45]:
sl = SINDyLibrary(latent_dim=1,
                 include_biases=True,
                 include_states=True,
                 include_sin=False,
                 include_cos=False,
                 include_multiply_pairs=False,
                 poly_order=2,
                 include_sqrt=False,
                 include_inverse=False,
                 include_sign_sqrt_of_diff=False,
                 device='cpu')

In [46]:
sl.get_feature_names()

['1', 'z0', 'z0*z0']

In [49]:
z = torch.tensor([[0,0], ])
z

tensor([[0, 0]])

In [50]:
theta = sl.transform(z)
theta

tensor([[1., 0., 0., 0.]])

In [21]:
from sindy_utils import *

In [22]:
n = 1 #dimensione latente
poly_order = 1

In [23]:
library_size(n, poly_order, use_sine=False, include_constant=False)

1

In [24]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
sindy_library(x, poly_order, include_sine=False)

array([[1., 1., 2., 3.],
       [1., 4., 5., 6.]])