In [1]:
from sindy_library_numpy import SINDyNumpy
import numpy as np
import itertools

In [2]:
sl = SINDyNumpy( latent_dim=2,
                 include_biases=False,
                 include_states=True,
                 include_sin=False,
                 include_cos=False,
                 include_multiply_pairs=False,
                 poly_order=2,
                 include_sqrt=False,
                 include_inverse=False,
                 include_sign_sqrt_of_diff=False,)

In [3]:
sl.feature_names

['z0', 'z1', 'z0*z0', 'z0*z1', 'z1*z1']

In [4]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
import torch
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
theta = sl.transform(x)
theta

array([[ 1,  2,  3,  1,  2,  4],
       [ 4,  5,  6, 16, 20, 25]])

In [7]:
theta.shape


(2, 6)

In [8]:
latent_dim = 3

In [9]:
possible_indicies = list(range(latent_dim))
possible_indicies

[0, 1, 2]

In [92]:
permuts = itertools.product(possible_indicies, possible_indicies)

In [95]:
for p in permuts:
    print(p)

(0, 1)
(0, 2)
(1, 0)
(1, 2)
(2, 0)
(2, 1)


In [96]:
permuts = [p for p in permuts if not p[0] == p[1]]
permuts

[(0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1)]

In [97]:
list(set([tuple(sorted(list(p))) for p in permuts]))

[(0, 1), (0, 2), (1, 2)]

In [ ]:
permuts = [p for p in permuts if not p[0] == p[1]]
self.idx_combis_non_commutative = permuts
self.idx_combis_commutative = list(set([tuple(sorted(list(p))) for p in permuts]))



if self.poly_order == 2:
    self.candidate_functions.append(self.poly_deg_2)
    names = []
    for i in range(self.latent_dim):
        for j in range(i, self.latent_dim):

    self.feature_names.extend(names)


In [ ]:
def poly_deg_2(z):
    result = 
    for i in range(latent_dim):
        for j in range(i, latent_dim):
            print(res
            res = z[:,i]*z[:,j]
            res = res.reshape(-1, 1)
            result.append(res)
    return np.concatenate(result, axis=1)

In [25]:
from sindy_library import *
import torch

In [45]:
sl = SINDyLibrary(latent_dim=1,
                 include_biases=True,
                 include_states=True,
                 include_sin=False,
                 include_cos=False,
                 include_multiply_pairs=False,
                 poly_order=2,
                 include_sqrt=False,
                 include_inverse=False,
                 include_sign_sqrt_of_diff=False,
                 device='cpu')

In [46]:
sl.get_feature_names()

['1', 'z0', 'z0*z0']

In [6]:
z = torch.tensor([[0,0], ])
z

NameError: name 'torch' is not defined

In [50]:
theta = sl.transform(z)
theta

tensor([[1., 0., 0., 0.]])

In [21]:
from sindy_utils import *

In [22]:
n = 1 #dimensione latente
poly_order = 1

In [23]:
library_size(n, poly_order, use_sine=False, include_constant=False)

1

In [24]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
sindy_library(x, poly_order, include_sine=False)

array([[1., 1., 2., 3.],
       [1., 4., 5., 6.]])

In [8]:
a = 4.45643
print(f'questo é {a:.3e}')

questo é 4.456e+00


In [1]:
import numpy as np

In [2]:
arrays = [np.random.randn(3, 4) for _ in range(10)]


(10, 3, 4)

In [5]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [ ]:
np.stack(arrays, axis=1).shape
np.stack(arrays, axis=2).shape
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))
np.stack((a, b), axis=-1)

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [18]:
c = np.stack((a, b,b),axis = 0)
c

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [19]:
allArrays = np.array([])
allArrays

array([], dtype=float64)

In [32]:
x = np.empty((10,2))
x

array([[4.68581434e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [24]:
np.random.randn(1,)

array([0.19649633])

In [29]:
for x in range(0, 10):
    myArray = np.random.randn(1,)
    allArrays = np.concatenate([allArrays, myArray])

In [30]:
allArrays.shape

(1010,)